services:
  database:
    container_name: postgresql-db
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres/data:/var/lib/postgres/data:rw
      - ./data/postgres/conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    env_file: .env.development.local
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGTZ: America/Bahia
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER}'"]
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 10
    
