import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MoreDrama",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} antialiased bg-background w-screen max-h-screen overflow-hidden box-border`}
      >
        <div className="max-h-screen overflow-y-scroll">
          <div className="max-w-mobile border mx-auto pt-10">
            <Header/>
            {children}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
